// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cluster/cluster.proto

package com.cell.grpc.cluster;

public interface GrpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int64 code = 2;</code>
   * @return The code.
   */
  long getCode();

  /**
   * <code>bytes data = 3;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
