// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/envelope.proto

package com.cell.grpc.common;

public interface EnvelopeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.Envelope)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes payload = 1;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
