scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'nacos_metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['nacos.demo.com:8080']
