// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/envelope.proto

package com.cell.grpc.common;

/**
 * Protobuf type {@code common.EnvelopeHeader}
 */
public  final class EnvelopeHeader extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:common.EnvelopeHeader)
    EnvelopeHeaderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EnvelopeHeader.newBuilder() to construct.
  private EnvelopeHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EnvelopeHeader() {
    protocol_ = "";
    sequenceId_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new EnvelopeHeader();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EnvelopeHeader(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            flag_ = input.readInt64();
            break;
          }
          case 16: {

            length_ = input.readInt64();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            protocol_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            sequenceId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return EvelopeProto.internal_static_common_EnvelopeHeader_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return EvelopeProto.internal_static_common_EnvelopeHeader_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            EnvelopeHeader.class, EnvelopeHeader.Builder.class);
  }

  public static final int FLAG_FIELD_NUMBER = 1;
  private long flag_;
  /**
   * <pre>
   * 0位代表的是大小端
   * </pre>
   *
   * <code>int64 flag = 1;</code>
   * @return The flag.
   */
  public long getFlag() {
    return flag_;
  }

  public static final int LENGTH_FIELD_NUMBER = 2;
  private long length_;
  /**
   * <code>int64 length = 2;</code>
   * @return The length.
   */
  public long getLength() {
    return length_;
  }

  public static final int PROTOCOL_FIELD_NUMBER = 3;
  private volatile Object protocol_;
  /**
   * <code>string protocol = 3;</code>
   * @return The protocol.
   */
  public String getProtocol() {
    Object ref = protocol_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      protocol_ = s;
      return s;
    }
  }
  /**
   * <code>string protocol = 3;</code>
   * @return The bytes for protocol.
   */
  public com.google.protobuf.ByteString
      getProtocolBytes() {
    Object ref = protocol_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      protocol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEQUENCEID_FIELD_NUMBER = 4;
  private volatile Object sequenceId_;
  /**
   * <code>string sequenceId = 4;</code>
   * @return The sequenceId.
   */
  public String getSequenceId() {
    Object ref = sequenceId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      sequenceId_ = s;
      return s;
    }
  }
  /**
   * <code>string sequenceId = 4;</code>
   * @return The bytes for sequenceId.
   */
  public com.google.protobuf.ByteString
      getSequenceIdBytes() {
    Object ref = sequenceId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      sequenceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (flag_ != 0L) {
      output.writeInt64(1, flag_);
    }
    if (length_ != 0L) {
      output.writeInt64(2, length_);
    }
    if (!getProtocolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, protocol_);
    }
    if (!getSequenceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sequenceId_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (flag_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, flag_);
    }
    if (length_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, length_);
    }
    if (!getProtocolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, protocol_);
    }
    if (!getSequenceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sequenceId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof EnvelopeHeader)) {
      return super.equals(obj);
    }
    EnvelopeHeader other = (EnvelopeHeader) obj;

    if (getFlag()
        != other.getFlag()) return false;
    if (getLength()
        != other.getLength()) return false;
    if (!getProtocol()
        .equals(other.getProtocol())) return false;
    if (!getSequenceId()
        .equals(other.getSequenceId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FLAG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFlag());
    hash = (37 * hash) + LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLength());
    hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
    hash = (53 * hash) + getProtocol().hashCode();
    hash = (37 * hash) + SEQUENCEID_FIELD_NUMBER;
    hash = (53 * hash) + getSequenceId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static EnvelopeHeader parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EnvelopeHeader parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EnvelopeHeader parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EnvelopeHeader parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EnvelopeHeader parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EnvelopeHeader parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EnvelopeHeader parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static EnvelopeHeader parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static EnvelopeHeader parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static EnvelopeHeader parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static EnvelopeHeader parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static EnvelopeHeader parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(EnvelopeHeader prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code common.EnvelopeHeader}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:common.EnvelopeHeader)
      EnvelopeHeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EvelopeProto.internal_static_common_EnvelopeHeader_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EvelopeProto.internal_static_common_EnvelopeHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EnvelopeHeader.class, EnvelopeHeader.Builder.class);
    }

    // Construct using com.cell.grpc.common.EnvelopeHeader.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      flag_ = 0L;

      length_ = 0L;

      protocol_ = "";

      sequenceId_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return EvelopeProto.internal_static_common_EnvelopeHeader_descriptor;
    }

    @Override
    public EnvelopeHeader getDefaultInstanceForType() {
      return EnvelopeHeader.getDefaultInstance();
    }

    @Override
    public EnvelopeHeader build() {
      EnvelopeHeader result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public EnvelopeHeader buildPartial() {
      EnvelopeHeader result = new EnvelopeHeader(this);
      result.flag_ = flag_;
      result.length_ = length_;
      result.protocol_ = protocol_;
      result.sequenceId_ = sequenceId_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof EnvelopeHeader) {
        return mergeFrom((EnvelopeHeader)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(EnvelopeHeader other) {
      if (other == EnvelopeHeader.getDefaultInstance()) return this;
      if (other.getFlag() != 0L) {
        setFlag(other.getFlag());
      }
      if (other.getLength() != 0L) {
        setLength(other.getLength());
      }
      if (!other.getProtocol().isEmpty()) {
        protocol_ = other.protocol_;
        onChanged();
      }
      if (!other.getSequenceId().isEmpty()) {
        sequenceId_ = other.sequenceId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      EnvelopeHeader parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (EnvelopeHeader) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long flag_ ;
    /**
     * <pre>
     * 0位代表的是大小端
     * </pre>
     *
     * <code>int64 flag = 1;</code>
     * @return The flag.
     */
    public long getFlag() {
      return flag_;
    }
    /**
     * <pre>
     * 0位代表的是大小端
     * </pre>
     *
     * <code>int64 flag = 1;</code>
     * @param value The flag to set.
     * @return This builder for chaining.
     */
    public Builder setFlag(long value) {

      flag_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0位代表的是大小端
     * </pre>
     *
     * <code>int64 flag = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlag() {

      flag_ = 0L;
      onChanged();
      return this;
    }

    private long length_ ;
    /**
     * <code>int64 length = 2;</code>
     * @return The length.
     */
    public long getLength() {
      return length_;
    }
    /**
     * <code>int64 length = 2;</code>
     * @param value The length to set.
     * @return This builder for chaining.
     */
    public Builder setLength(long value) {

      length_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 length = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLength() {

      length_ = 0L;
      onChanged();
      return this;
    }

    private Object protocol_ = "";
    /**
     * <code>string protocol = 3;</code>
     * @return The protocol.
     */
    public String getProtocol() {
      Object ref = protocol_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        protocol_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string protocol = 3;</code>
     * @return The bytes for protocol.
     */
    public com.google.protobuf.ByteString
        getProtocolBytes() {
      Object ref = protocol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        protocol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string protocol = 3;</code>
     * @param value The protocol to set.
     * @return This builder for chaining.
     */
    public Builder setProtocol(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      protocol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string protocol = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtocol() {

      protocol_ = getDefaultInstance().getProtocol();
      onChanged();
      return this;
    }
    /**
     * <code>string protocol = 3;</code>
     * @param value The bytes for protocol to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      protocol_ = value;
      onChanged();
      return this;
    }

    private Object sequenceId_ = "";
    /**
     * <code>string sequenceId = 4;</code>
     * @return The sequenceId.
     */
    public String getSequenceId() {
      Object ref = sequenceId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sequenceId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string sequenceId = 4;</code>
     * @return The bytes for sequenceId.
     */
    public com.google.protobuf.ByteString
        getSequenceIdBytes() {
      Object ref = sequenceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sequenceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sequenceId = 4;</code>
     * @param value The sequenceId to set.
     * @return This builder for chaining.
     */
    public Builder setSequenceId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      sequenceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sequenceId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSequenceId() {

      sequenceId_ = getDefaultInstance().getSequenceId();
      onChanged();
      return this;
    }
    /**
     * <code>string sequenceId = 4;</code>
     * @param value The bytes for sequenceId to set.
     * @return This builder for chaining.
     */
    public Builder setSequenceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      sequenceId_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:common.EnvelopeHeader)
  }

  // @@protoc_insertion_point(class_scope:common.EnvelopeHeader)
  private static final EnvelopeHeader DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new EnvelopeHeader();
  }

  public static EnvelopeHeader getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EnvelopeHeader>
      PARSER = new com.google.protobuf.AbstractParser<EnvelopeHeader>() {
    @Override
    public EnvelopeHeader parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EnvelopeHeader(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EnvelopeHeader> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<EnvelopeHeader> getParserForType() {
    return PARSER;
  }

  @Override
  public EnvelopeHeader getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

