// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/envelope.proto

package com.cell.grpc.common;

public interface HeaderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:common.Header)
        com.google.protobuf.MessageOrBuilder
{
}
