#scrape_configs:
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['localhost:9090']
#  #  - job_name: 'nacos_metrics'
#  #    scrape_interval: 10s
#  #    static_configs:
#  #      - targets: ['nacos.demo.com:8080']
#  #    metrics_path: /actuator/prometheus
#  - job_name: 'file_ds'
#    file_sd_configs:
#      - files:
#          - prometheus_targets/*.yaml
#    metrics_path: /actuator/prometheus
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'nacos-prometheus'
    metrics_path: '/actuator/prometheus'
    consul_sd_configs:
      - server: 'nacos.discovery.com:8080'
        services: []