// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cluster/cluster.proto

package com.cell.grpc.common.cluster;

import com.cell.grpc.common.Envelope;
import com.cell.grpc.common.EnvelopeOrBuilder;

public interface GrpcRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:GrpcRequest)
        com.google.protobuf.MessageOrBuilder
{

    /**
     * <code>.common.Envelope envelope = 1;</code>
     *
     * @return Whether the envelope field is set.
     */
    boolean hasEnvelope();

    /**
     * <code>.common.Envelope envelope = 1;</code>
     *
     * @return The envelope.
     */
    Envelope getEnvelope();

    /**
     * <code>.common.Envelope envelope = 1;</code>
     */
    EnvelopeOrBuilder getEnvelopeOrBuilder();
}
